server_default_applications:
  - tar
  - python
  - python-pip
  - python-setuptools
  - python-apt
  - python3
  - python3-pip
  - python3-setuptools
  - python3-apt
  - unzip
  - curl
  - screen
  - wget
  - iptables
  - openssh-server