- name: Update /etc/hosts
  become: true
  template:
    src: 'hosts.j2'
    dst: /etc/hosts
    mode: 0644
  tags: common, local_dns, hosts

- name: Update system to APT servers
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags: common, apt

- name: Install default server application programs
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes 
  with_items: "{{ server_default_application_programs }}"
  tags: common, server_default_applications