- name: Update /etc/hosts
  become: true
  template:
    src: 'hosts.j2'
    dst: /etc/hosts
    mode: 0644
  tags: common, local_dns, hosts

# - name: Update /etc/hosts
#   become: true
#   blockinfile:
#       path: /etc/hosts
#       create: yes
#       block: |
#         127.0.0.1 localhost

#         # The following lines are desirable for IPv6 capable hosts
#         ::1 ip6-localhost ip6-loopback
#         fe00::0 ip6-localnet
#         ff00::0 ip6-mcastprefix
#         ff02::1 ip6-allnodes
#         ff02::2 ip6-allrouters
#         ff02::3 ip6-allhosts

#         {% for item in ansible_play_batch %}
#         {{ hostvars[item].ansible_ssh_host }}   {{ item }}    
#         {% endfor %}
#   tags: common, local_dns, hosts

- name: Update system to APT servers
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags: common, apt

- name: Install default server application programs
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes 
  with_items: "{{ server_default_application_programs }}"
  tags: common, server_default_applications